# Introducción a NumPy

*Hasta ahora hemos visto los tipos de datos más básicos que nos ofrece Python: integer, real, complex, boolean, list, tuple...  En este notebook nos adentraremos en el paquete NumPy: aprenderemos a crear distintos arrays y a operar con ellos*.

## ¿Qué es un array? 

Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* nos _recuerdan_ a los vectores, matrices, tensores...
* podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__¿Qué solemos guardar en arrays?__

* Vectores y matrices.
* Datos de experimentos:
    - En distintos instantes discretos.
    - En distintos puntos del espacio.
* Resultado de evaluar funciones con los datos anteriores.
* Discretizaciones para usar algoritmos de: integración, derivación, interpolación...

## ¿Qué es NumPy?

NumPy es un paquete fundamental para la programación científica que proporciona un __objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.
Para usar NumPy lo primero que debemos hacer es importarlo:

In [2]:
import numpy as np
#para ver la versión que tenemos instalada:
np.__version__

'1.18.5'

## Nuestro primer array

Creemos nuestros primeros arrays:

In [2]:
import numpy as np

In [3]:
# Array de una dimensión
mi_primer_array = np.array([1, 2, 3, 4]) 
mi_primer_array

array([1, 2, 3, 4])

In [4]:
# Podemos usar print
print(mi_primer_array)

[1 2 3 4]


In [5]:
# Comprobar el tipo de mi_primer_array
type(mi_primer_array)

numpy.ndarray

In [6]:
# Comprobar el tipo de datos que contiene
mi_primer_array.dtype

dtype('int64')

Los arrays de una dimensión se crean pasándole una lista como argumento a la función `np.array`. Para crear un array de dos dimensiones le pasaremos una _lista de listas_:

In [8]:
# Array de dos dimensiones
mi_segundo_array = np.array([[1, 2, 3], \
                             [4, 5, 6], \
                             [7, 8, 9]])

<div class="alert alert-info"><strong>Nota:</strong> 
Podemos continuar en la siguiente línea usando `\`
</div>

En forma alternativa, es posible definir el cambio de linea de acuerdo al [PEP 8 (indentation)](http://legacy.python.org/dev/peps/pep-0008/#indentation):

In [9]:
mi_segundo_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]) 

### Funciones y constantes de NumPy

Hemos dicho que NumPy también incorpora __funciones__. Un ejemplo sencillo:

In [10]:
# Suma
np.sum(mi_primer_array)

10

In [11]:
# Máximo
np.max(mi_primer_array)

4

In [15]:
# Seno
np.sin(mi_segundo_array)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

Y algunas __constantes__ que podemos necesitar:

In [12]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

## Funciones para crear arrays

Ya hemos visto que la función `np.array()` nos permite crear arrays con los valores que nosotros introduzcamos manualmente a través de listas. Más adelante, aprenderemos a leer ficheros y almacenarlos en arrays. Mientras tanto, ¿qué puede hacernos falta?

#### array de ceros

In [13]:
# En una dimensión
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# En dos dimensiones
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

<div class="alert alert-info"><strong>Nota:</strong> 
En el caso 1D es válido tanto `np.zeros([5])` como `np.zeros(5)` (sin los corchetes), pero no lo será para el caso nD
</div>

#### array "vacío"

In [18]:
np.empty(10)

array([6.94038096e-310, 4.66671046e-310, 6.94037529e-310, 6.94037529e-310,
       6.94038115e-310, 6.94037999e-310, 6.94037529e-310, 6.94038116e-310,
       6.94037529e-310, 6.94037529e-310])

<div class="alert alert-success"><strong>Importante:</strong> 
El array vacío se crea en un tiempo algo inferior al array de ceros. Sin embargo, el valor de sus elementos será arbitrario y dependerá del estado de la memoria. Al utilizarlo debemos asegurarnos de que luego llenamos bien todos sus elementos porque podríamos introducir resultados erróneos.
</div>

#### array de unos

In [19]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### array identidad

In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<div class="alert alert-info"><strong>Nota:</strong> 
También podemos probar `np.eye()` y `np.diag()`.
</div>

### Rangos

#### np.arange

NumPy, danos __un array que vaya de 0 a 5__:

In [20]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

__Miremos con atención el resultado anterior ... el último elemento no es 5 sino 4 !!!__

NumPy, danos __un array que vaya de 0 a 10, de 3 en 3__:

In [24]:
np.arange(10, 11, 0.05)

array([10.  , 10.05, 10.1 , 10.15, 10.2 , 10.25, 10.3 , 10.35, 10.4 ,
       10.45, 10.5 , 10.55, 10.6 , 10.65, 10.7 , 10.75, 10.8 , 10.85,
       10.9 , 10.95])

#### np.linspace

Si hemos *tenido* que usar MATLAB alguna vez, seguro que esto nos suena familiar:

In [25]:
np.linspace(0, 10, 200)

array([ 0.        ,  0.05025126,  0.10050251,  0.15075377,  0.20100503,
        0.25125628,  0.30150754,  0.35175879,  0.40201005,  0.45226131,
        0.50251256,  0.55276382,  0.60301508,  0.65326633,  0.70351759,
        0.75376884,  0.8040201 ,  0.85427136,  0.90452261,  0.95477387,
        1.00502513,  1.05527638,  1.10552764,  1.15577889,  1.20603015,
        1.25628141,  1.30653266,  1.35678392,  1.40703518,  1.45728643,
        1.50753769,  1.55778894,  1.6080402 ,  1.65829146,  1.70854271,
        1.75879397,  1.80904523,  1.85929648,  1.90954774,  1.95979899,
        2.01005025,  2.06030151,  2.11055276,  2.16080402,  2.21105528,
        2.26130653,  2.31155779,  2.36180905,  2.4120603 ,  2.46231156,
        2.51256281,  2.56281407,  2.61306533,  2.66331658,  2.71356784,
        2.7638191 ,  2.81407035,  2.86432161,  2.91457286,  2.96482412,
        3.01507538,  3.06532663,  3.11557789,  3.16582915,  3.2160804 ,
        3.26633166,  3.31658291,  3.36683417,  3.41708543,  3.46

En este caso **sí** se incluye el último elemento.

<div class="alert alert-info"><strong>Nota:</strong> 
También podemos probar `np.logspace()`
</div>

### reshape

Con `np.arange()` es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues sí, pero no usando una sola función. Imaginemos que deseamos crear algo como esto:

\begin{pmatrix}
    1 & 2 & 3\\ 
    4 & 5 & 6\\
    7 & 8 & 9\\
    \end{pmatrix}
    
* Comenzaremos por crear un array 1d con los valores $(1,2,3,4,5,6,7,8,9)$ usando `np.arange()`.
* Luego le daremos forma de array 2d con `np.reshape(array, (dim0, dim1))`.

In [26]:
a = np.arange(1, 10)
M = np.reshape(a, [3, 3])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# También funciona como método
N = a.reshape([3,3])
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<div class="alert alert-info"><strong>Nota:</strong> 
Debemos saber que los <b>métodos</b> están asociados a la programación orientada a objetos y que en Python <i>todo</i> es un objeto. Podemos pensarlos como <i>funciones especiales</i> en las que el argumento más importante (sobre el que se realiza la acción) se escribe delante seguido de un punto. 
</div>

## Operaciones

### Operaciones elemento a elemento

Probemos hacer ahora algunas operaciones con *arrays*. El funcionamiento es el habitual en FORTRAN y MATLAB y poco hay que añadir:

In [28]:
#crear un array y sumarle un número
arr = np.arange(11)
arr + 55

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [29]:
#multiplicarlo por un número
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
#elevarlo al cuadrado
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
#calcular una función
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

<div class="alert alert-info"><strong>Entrenamiento:</strong> 
Podemos tratar de comparar la diferencia de tiempo entre realizar la operación en bloque, como ahora, y realizarla elemento a elemento, recorriendo el array con un bucle.
</div>

__Si las operaciones involucran dos arrays también se realizan elemento a elemento__

In [34]:
#creamos dos arrays
arr1 = np.arange(0, 11)
arr2 = np.arange(20, 31)

In [37]:
#los sumamos
print(arr1)
print(arr2)
arr1 + arr2

[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30]


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [38]:
#multiplicamos
arr1 * arr2

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

#### Comparaciones

In [39]:
# >,<
arr1 > arr2

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [35]:
# ==
arr1 == arr2 # ¡ojo! los arrays son de integers, no de floats

array([False, False, False, False, False, False, False, False, False,
       False, False])

_En definitiva:_
* __Ingenieros y científicos $\dfrac{u\dot(2)}{a+b}\heartsuit$ arrays!__
* __Ingenieros y científicos necesitan NumPy.__

Algunos enlaces:

* [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html).
* [NumPy and IPython SciPy 2013 Tutorial](http://conference.scipy.org/scipy2013/tutorial_detail.php?id=100).
* [NumPy and SciPy documentation](http://docs.scipy.org/doc/).

In [1]:
# Esta celda da el estilo al notebook
from IPython.core.display import HTML
css_file = '../styles/aeropython.css'
HTML(open(css_file, "r").read())